name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
        shell: bash
    
      - run: echo "$REPOSITORY_NAME"
        shell: bash
#      - name: checkout code
#        uses: actions/checkout@v2
#      - name: install buildx
#        id: buildx
#        uses: crazy-max/ghaction-docker-buildx@v1
#        with:
#          version: latest
#      - name: login to docker hub
#        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
#      - name: build the image
#        run: |
#          docker buildx build --push \
#            --tag ${{ secrets.DOCKER_REPO }}:latest \
#            --platform linux/amd64,linux/arm64 .

